name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 25.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate and Extract Changelog
        id: extract_changelog
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"

          FIRST_VERSION=$(grep -Po '^- \[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)

          if [ "$FIRST_VERSION" != "$VERSION" ]; then
            echo "::error ::CHANGELOG.md's latest version '$FIRST_VERSION' does not match input version '$VERSION'"
            exit 1
          fi

          awk -v ver="$VERSION" '
            $0 ~ "^##[[:space:]]+" ver " -" { in_section=1; next }
            in_section {
              if ($0 ~ "^##[[:space:]]+") exit
              print
            }
          ' CHANGELOG.md > latest_changelog.txt

          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
          cat latest_changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.53.2

      - name: Configure JFrog CLI with Basic Auth
        run: |
          jf c add artifactory-server \
            --url="https://pull.artifacts.ni.com/artifactory" \
            --user="${{ secrets.JFROG_USERNAME }}" \
            --password="${{ secrets.JFROG_PASSWORD }}" \
            --enc-password=false \
            --basic-auth-only
          jf c use artifactory-server

      - name: Download .nupkg from Artifactory
        run: |
          VERSION="${{ github.event.inputs.version }}"
          FILENAME="NationalInstruments.SemiconductorTestLibrary.$VERSION.nupkg"
          jf rt dl "rnd-nuget-ci/NationalInstruments.SemiconductorTestLibrary/$FILENAME" "$FILENAME"

      - name: Create Draft Release and Attach Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: |
            ${{ steps.extract_changelog.outputs.changelog_section }}
          draft: true
          files: |
            NationalInstruments.SemiconductorTestLibrary.${{ github.event.inputs.version }}.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
