name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 25.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed to create tags & releases

jobs:
  create-draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract and Validate Latest Changelog
        id: extract_changelog
        run: |
          # Use the provided input version
          VERSION="${{ github.event.inputs.version }}"  # e.g., "25.0.0"
          TAG="v$VERSION"
          
          echo "Validating version: $VERSION"
          echo "-------- Contents of CHANGELOG.md --------"
          cat CHANGELOG.md
          echo "------------------------------------------"

          # Extract the first version number from list items 
          # For example, from: "- [25.0.0 - 2025-04-11](#2500---2025-04-11)"
          FIRST_VERSION=$(grep -Po '^\s*-\s*\[\s*\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
          
          echo "Extracted FIRST_VERSION from CHANGELOG.md: '$FIRST_VERSION'"

          if [ "$FIRST_VERSION" != "$VERSION" ]; then
            echo "::error ::CHANGELOG.md's latest version '$FIRST_VERSION' does not match input version '$VERSION'"
            exit 1
          fi

          echo "Versions match. Extracting detailed changelog section..."

          # Extract changelog section from the Markdown heading that starts with "## 25.0.0 -"
          awk -v ver="$VERSION" '
            $0 ~ "^[[:space:]]*##[[:space:]]+" ver " -" { in_section=1; next }
            in_section {
              if ($0 ~ "^[[:space:]]*##[[:space:]]+") exit
              print
            }
          ' CHANGELOG.md > latest_changelog.txt

          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
          cat latest_changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Git Tag if not exists
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"
          echo "Using TAG: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping creation."
          else
            echo "Creating tag $TAG"
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Configure JFrog CLI
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}        # e.g., "https://pull.artifacts.ni.com/artifactory"
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          echo "Installing and configuring JFrog CLI..."
          # Download JFrog CLI if not already installed
          curl -fL https://jfrog.com/download-jfrog-cli/cli-linux-amd64/jfrog -o jfrog
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/
          jfrog --version
          # Configure the JFrog CLI using secure environment variables.
          jfrog config add ni-jfrog \
            --url="$JFROG_URL" \
            --user="$JFROG_USERNAME" \
            --password="$JFROG_PASSWORD" \
            --interactive=false

      - name: Download NuGet Package from JFrog
        env:
          VERSION: ${{ github.event.inputs.version }}  # e.g., "25.0.0"
        run: |
          # Construct the expected file name and full path
          FILE_NAME="NationalInstruments.SemiconductorTestLibrary.${VERSION}.nupkg"
          JFROG_REPO_PATH="${{ secrets.JFROG_REPO_PATH }}"
          FULL_PATH="${JFROG_REPO_PATH}/${FILE_NAME}"
          
          echo "Downloading NuGet package from JFrog at path: $FULL_PATH"
          # Download only the specific NuGet package with --flat=true to avoid creating extra directories.
          jfrog rt dl "$FULL_PATH" --flat=true
          
          ls -l

      - name: Create Draft Release and Attach Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: |
            **Release Notes:**
            ${{ steps.extract_changelog.outputs.changelog_section }}
          draft: true
          files: |
            *.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # The following artifact download steps remain commented out for now.
      # They can be re-enabled when additional artifacts are to be fetched.
      # - name: Download Additional Artifacts from JFrog
      #   id: download_artifacts
      #   run: |
      #     set -e
      #     VERSION="${{ github.event.inputs.version }}"
      #     BASE_URL="https://<our-jfrog-domain>.jfrog.io/artifactory/<our-repo>/releases"
      #     
      #     curl_retry() {
      #       local url=$1
      #       local output=$2
      #       for i in {1..3}; do
      #         echo "Attempt $i to download $url"
      #         if curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }}" -fL "$url" -o "$output"; then
      #           echo "Downloaded $output"
      #           return 0
      #         fi
      #         echo "Retrying in 5s..."
      #         sleep 5
      #       done
      #       echo "::error ::Failed to download $url after 3 attempts"
      #       return 1
      #     }
      #     
      #     echo "Downloading additional .nupkg..."
      #     curl_retry "$BASE_URL/${VERSION}.nupkg" "${VERSION}.nupkg"
      #     
      #     mkdir -p assemblies
      #     declare -a components=("NationalInstruments.SemiconductorTestLibrary.Abstractions" "NationalInstruments.SemiconductorTestLibrary.Extensions" "NationalInstruments.SemiconductorTestLibrary.TestStandSteps")
      #     declare -a extensions=("dll" "pdb" "xml")
      #     
      #     for component in "${components[@]}"; do
      #       for ext in "${extensions[@]}"; do
      #         FILENAME="${component}.${ext}"
      #         URL="$BASE_URL/$FILENAME"
      #         OUTFILE="assemblies/$FILENAME"
      #         if ! curl_retry "$URL" "$OUTFILE"; then
      #           echo "::warning ::$FILENAME not found or failed to download."
      #         fi
      #       done
      #     done
      #     
      #     echo "Creating assemblies.zip..."
      #     cd assemblies
      #     if [ "$(ls -1 | wc -l)" -eq 0 ]; then
      #       echo "::error ::No files in assemblies/. Aborting zip creation."
      #       exit 1
      #     fi
      #     zip ../assemblies.zip *
      #     cd ..
      #
      # - name: Upload Additional Release Assets (Attach assemblies.zip)
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ github.event.inputs.version }}
      #     files: |
      #       assemblies.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
