name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 25.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed to create tags & releases

jobs:
  create-draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract and Validate Latest Changelog
        id: extract_changelog
        run: |
          VERSION="${{ github.event.inputs.version }}"  # e.g., "25.0.0"
          TAG="v$VERSION"
          
          echo "Validating version: $VERSION"
          echo "-------- Contents of CHANGELOG.md --------"
          cat CHANGELOG.md
          echo "------------------------------------------"
          
          FIRST_VERSION=$(grep -Po '^\s*-\s*\[\s*\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
          echo "Extracted FIRST_VERSION from CHANGELOG.md: '$FIRST_VERSION'"
          
          if [ "$FIRST_VERSION" != "$VERSION" ]; then
            echo "::error ::CHANGELOG.md's latest version '$FIRST_VERSION' does not match input version '$VERSION'"
            exit 1
          fi
          
          echo "Versions match. Extracting detailed changelog section..."
          awk -v ver="$VERSION" '
            $0 ~ "^[[:space:]]*##[[:space:]]+" ver " -" { in_section=1; next }
            in_section {
              if ($0 ~ "^[[:space:]]*##[[:space:]]+") exit
              print
            }
          ' CHANGELOG.md > latest_changelog.txt
          
          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
          cat latest_changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Git Tag if not exists
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TAG="v$VERSION"
          echo "Using TAG: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping creation."
          else
            echo "Creating tag $TAG"
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Download NuGet Package from JFrog using HTTP
        env:
          VERSION: ${{ github.event.inputs.version }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          # Prepare NuGet file URL
          FILE_NAME="NationalInstruments.SemiconductorTestLibrary.${VERSION}.nupkg"
          FILE_URL="https://pull.artifacts.ni.com/artifactory/rnd-nuget-ci/NationalInstruments.SemiconductorTestLibrary/${FILE_NAME}"

          echo "Downloading NuGet package from JFROG at: $FILE_URL"

          # Base64 encode credentials
          AUTH_STRING="${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }}"
          BASIC_AUTH=$(echo -n "$AUTH_STRING" | base64)

          # Download the file using Node.js HTTP request
          node -e "
            const http = require('https');
            const fs = require('fs');
            const url = '$FILE_URL';
            const auth = 'Basic ' + '$BASIC_AUTH';

            const file = fs.createWriteStream('$FILE_NAME');
            http.get(url, { headers: { 'Authorization': auth } }, (response) => {
              if (response.statusCode === 200) {
                response.pipe(file);
                file.on('finish', () => {
                  console.log('Download complete: $FILE_NAME');
                  file.close();
                });
              } else {
                console.error('Failed to download file. Status Code: ' + response.statusCode);
                process.exit(1);
              }
            }).on('error', (err) => {
              console.error('Error: ' + err.message);
              process.exit(1);
            });
            "

      - name: Create Draft Release and Attach Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: |
            **Release Notes:**
            ${{ steps.extract_changelog.outputs.changelog_section }}
          draft: true
          files: |
            *.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
