name: Create AzDo Work Item on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_azdo_work_item:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract Issue Details and Ensure Proper Escaping
      - name: Extract Issue Details
        id: issue
        run: |
          echo "title=$(echo '${{ github.event.issue.title }}' | jq -Rr @sh)" >> $GITHUB_ENV
          echo "body=$(echo '${{ github.event.issue.body }}' | jq -Rr @sh)" >> $GITHUB_ENV
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "issue_url=${{ github.event.issue.html_url }}" >> $GITHUB_ENV

      # Step 2: Determine Work Item Type Based on GitHub Labels
      - name: Determine Work Item Type
        id: work_item_type
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r 'map(.name) | join(", ")')
          TYPE="Customer Escalation"

          if echo "$LABELS" | grep -qi 'enhancement'; then 
            TYPE="User Story"
          elif echo "$LABELS" | grep -qi 'bug'; then
            TYPE="Bug"
          fi
    
          echo "work_item_type=$TYPE" >> $GITHUB_ENV
          echo "labels=$LABELS" >> $GITHUB_ENV

      # Step 3: Ensure jq is Installed
      - name: Install jq (if missing)
        run: sudo apt-get install jq -y

      # Step 4: Notify Developers via Microsoft Teams
      - name: Notify Developers via Microsoft Teams
        run: |
          MESSAGE=$(jq -n \
            --arg title "${{ env.title }}" \
            --arg body "${{ env.body }}" \
            --arg issue_url "${{ env.issue_url }}" \
            --arg issue_number "#${{ env.issue_number }}" \
            --arg labels "${{ env.labels }}" \
            --arg type "${{ env.work_item_type }}" \
            '{
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "New GitHub Issue Assigned",
              "sections": [{
                "activityTitle": "**New GitHub Issue Created**",
                "facts": [
                  { "name": "Title", "value": $title },
                  { "name": "Issue Number", "value": $issue_number },
                  { "name": "Labels", "value": $labels },
                  { "name": "Type", "value": $type },
                  { "name": "GitHub Issue", "value": "[View Issue](" + $issue_url + ")" },
                  { "name": "Description", "value": $body }
                ],
                "markdown": true
              }]
            }')

          curl -H "Content-Type: application/json" -d "$MESSAGE" ${{ secrets.TEAMS_WEBHOOK_URL }}
