name: Create AzDo Work Item on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_azdo_work_item:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract details of the issue
      - name: Extract issue details
        id: issue
        run: |
          echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "body=${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "issue_url=${{ github.event.issue.html_url }}" >> $GITHUB_ENV
      
      # Step 2: Determine Work Item type that should be created in AzDo based on tag on the Github issue
      # Check if casing in labels is correct.
      - name: Determine Work Item Type
        id: work_item_type
        run: |
          LABELS="${{ toJson(github.event.issue.labels) }}"
          TYPE="Customer Escalation"

          if echo "$LABELS" | grep -q '"name": "enhancement"'; then 
            TYPE="User Story"
          elif echo "$LABELS" | grep -q '"name": "bug"'; then
            TYPE="Bug"
          fi
    
          echo "work_item_type=$TYPE" >> $GITHUB_ENV

      # Step 3: Notify Developers via Microsoft Teams **BEFORE** creating the work item
      - name: Notify Developers via Microsoft Teams
        run: |
          MESSAGE=$(jq -n \
            --arg title "${{ github.event.issue.title }}" \
            --arg body "${{ github.event.issue.body }}" \
            --arg issue_url "${{ github.event.issue.html_url }}" \
            --arg type "${{ env.work_item_type }}" \
            '{
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "New GitHub Issue Assigned",
              "sections": [{
                "activityTitle": "**New GitHub Issue Created**",
                "facts": [
                  { "name": "Title", "value": $title },
                  { "name": "Type", "value": $type },
                  { "name": "GitHub Issue", "value": "[" + $title + "](" + $issue_url + ")" }
                ],
                "markdown": true
              }]
            }')

          curl -H "Content-Type: application/json" -d "$MESSAGE" ${{ secrets.TEAMS_WEBHOOK_URL }}