name: Create AzDo Work Item on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_azdo_work_item:
    runs-on: ubuntu-latest

    steps:
      # Step 1 Ensure jq is installed
      - name: Install jq (if missing)
        run: sudo apt-get install jq -y

      # Step 2: Extract issue details safely
      - name: Extract Issue Details
        id: issue
        run: |
          echo "title=$(echo '${{ github.event.issue.title }}' | jq -Rr @json)" >> $GITHUB_ENV
          echo "body=$(echo '${{ github.event.issue.body }}' | jq -Rr @json)" >> $GITHUB_ENV
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "issue_url=${{ github.event.issue.html_url }}" >> $GITHUB_ENV
          echo "labels=$(echo '${{ github.event.issue.labels }}' | jq -Rr @json)" >> $GITHUB_ENV

      # Step 3: Determine Work Item Type Based on Labels
      - name: Determine Work Item Type
        id: work_item_type
        run: |
          LABELS="${{ env.labels }}"
          TYPE="Customer Escalation"
          
          if echo "$LABELS" | grep -qi 'enhancement'; then 
            TYPE="User Story"
          elif echo "$LABELS" | grep -qi 'bug'; then
            TYPE="Bug"
          fi
          
          echo "work_item_type=$TYPE" >> $GITHUB_ENV

      # Step 4: Notify Developers via Microsoft Teams
      - name: Notify Developers via Microsoft Teams
        run: |
          MESSAGE=$(jq -n \
            --arg title "$title" \
            --arg body "$body" \
            --arg issue_url "$issue_url" \
            --arg issue_number "$issue_number" \
            --arg type "$work_item_type" \
            --arg mentionText "<at>@everyone</at>" \
            --arg mentionId "29:1Lkg0a7..." \ # Replace with the actual ID for @everyone
            '{
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "New GitHub Issue Assigned",
              "sections": [{
                "activityTitle": "**New GitHub Issue Created**",
                "facts": [
                  { "name": "Title", "value": $title },
                  { "name": "Issue Number", "value": ("#" + $issue_number) },
                  { "name": "GitHub Issue", "value": $issue_url },
                  { "name": "Description", "value": $body }
                ],
                "markdown": true
              }],
              "potentialAction": [{
                "@type": "OpenUri",
                "name": "View Issue",
                "targets": [{ "os": "default", "uri": $issue_url }]
              }],
              "text": $mentionText,
              "mentions": [{
                "type": "Mention",
                "text": $mentionText,
                "id": $mentionId
              }]
            }')

          curl -H "Content-Type: application/json" -d "$MESSAGE" ${{ secrets.TEAMS_WEBHOOK_URL }}